### 회원가입
POST localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "email" : "test@test.com",
  "password": "test",
  "name": "test"
}

### 로그인
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email" : "test@test.com",
  "password": "test"
}

### me
GET localhost:8080/api/v1/users/me

### 로그아웃
POST localhost:8080/api/v1/auth/logout

### me
GET localhost:8080/api/v1/users/me